repos:
  - repo: local
    hooks:
      - id: biome
        name: biome check
        language: system
        entry: node_modules/.bin/biome check .
        pass_filenames: false
      - id: knip
        name: knip
        language: system
        entry: node_modules/.bin/knip
        pass_filenames: false
